Add files via upload

diff --git a/patches/docker/Makefile b/patches/docker/Makefile
--- a/patches/docker/Makefile
+++ b/patches/docker/Makefile
@@ -11,80 +11,61 @@ PKG_GIT_URL:=github.com/docker/cli
 PKG_GIT_REF:=v$(PKG_VERSION)
 PKG_SOURCE_URL:=https://codeload.$(PKG_GIT_URL)/tar.gz/$(PKG_GIT_REF)?
 PKG_HASH:=c5fadbc00c02dbecb1b7c9936e188baf9c80421a9107e7e9ad36a0923a0fc764
-PKG_GIT_SHORT_COMMIT:=88096ef
+PKG_GIT_SHORT_COMMIT:=88096ef # SHA1 used within the docker executables
 
 PKG_MAINTAINER:=Gerard Ryan <G.M0N3Y.2503@gmail.com>
 
 PKG_BUILD_DEPENDS:=golang/host dockerd
 PKG_BUILD_PARALLEL:=1
+PKG_BUILD_FLAGS:=no-mips16
 
 GO_PKG:=$(PKG_GIT_URL)
 
 include $(INCLUDE_DIR)/package.mk
-include ../../lang/golang/golang-package.mk
-
-EMPTY:=
-SPACE:=$(EMPTY) $(EMPTY)
-
-ARCH_DEPENDS:=@($(subst $(SPACE),||,$(strip $(filter-out mips mips64 mipsel mips64el,$(subst ||,$(SPACE),$(patsubst @(%),%,$(GO_ARCH_DEPENDS)))))))
+include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk
 
 define Package/docker
-	SECTION:=utils
-	CATEGORY:=Utilities
-	TITLE:=Docker Community Edition CLI
-	URL:=https://www.docker.com/
-	DEPENDS:=$(ARCH_DEPENDS)
+  SECTION:=utils
+  CATEGORY:=Utilities
+  TITLE:=Docker Community Edition CLI
+  URL:=https://www.docker.com/
+  DEPENDS:=$(GO_ARCH_DEPENDS)
 endef
 
 define Package/docker/description
-	The CLI used in the Docker CE and Docker EE products.
+The CLI used in the Docker CE and Docker EE products.
 endef
 
 GO_PKG_INSTALL_EXTRA:=\
 	cli/compose/schema/data \
+	vendor/github.com/santhosh-tekuri/jsonschema/v6/metaschemas \
 	vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
-
+    
 TAR_OPTIONS:=--strip-components 1 $(TAR_OPTIONS)
 TAR_CMD=$(HOST_TAR) -C $(1) $(TAR_OPTIONS)
-
-TARGET_LDFLAGS += $(if $(CONFIG_USE_GLIBC),-lc -lgcc)
-
-# Verify PKG_GIT_SHORT_COMMIT
+TARGET_LDFLAGS += $(if $(CONFIG_USE_GLIBC),-lc -lgcc_eh)
 
 define Build/Prepare
 	$(Build/Prepare/Default)
-	EXPECTED_PKG_GIT_SHORT_COMMIT=$$$$( $(CURDIR)/../dockerd/git-short-commit.sh '$(PKG_GIT_URL)' '$(PKG_GIT_REF)' '$(TMP_DIR)/git-short-commit/$(PKG_NAME)-$(PKG_VERSION)' ); \
-	if [ "$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}" != "$(strip $(PKG_GIT_SHORT_COMMIT))" ]; then \
-		echo "ERROR: Expected 'PKG_GIT_SHORT_COMMIT:=$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}', found 'PKG_GIT_SHORT_COMMIT:=$(strip $(PKG_GIT_SHORT_COMMIT))'"; \
-		exit 1; \
-	fi
-endef
 
-# Docker CLI 29.8.0 jsonschema/v6 fix
-
-define Build/PrepareJsonschema
-	cd "$(PKG_BUILD_DIR)/.go_work/build/src/github.com/docker/cli"; \
-	$(GO_PKG_VARS) \
-	go mod download -modcacherw; \
-	mkdir -p "$(PKG_BUILD_DIR)/.go_work/build/src/github.com/docker/cli/vendor/github.com/santhosh-tekuri/jsonschema/v6"; \
-	rm -rf "$(PKG_BUILD_DIR)/.go_work/build/src/github.com/docker/cli/vendor/github.com/santhosh-tekuri/jsonschema/v6/metaschemas"; \
-	cp -a "$$(find "$(GO_MOD_CACHE_DIR)/github.com/santhosh-tekuri/jsonschema" \
-		-maxdepth 2 \
-		-type d \
-		-name 'v6@*' \
-		-print \
-		-quit)/metaschemas" \
-		"$(PKG_BUILD_DIR)/.go_work/build/src/github.com/docker/cli/vendor/github.com/santhosh-tekuri/jsonschema/v6/"
+	# Verify PKG_GIT_SHORT_COMMIT
+	( \
+		EXPECTED_PKG_GIT_SHORT_COMMIT=$$$$( $(CURDIR)/../dockerd/git-short-commit.sh '$(PKG_GIT_URL)' '$(PKG_GIT_REF)' '$(TMP_DIR)/git-short-commit/$(PKG_NAME)-$(PKG_VERSION)' ); \
+		if [ "$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}" != "$(strip $(PKG_GIT_SHORT_COMMIT))" ]; then \
+			echo "ERROR: Expected 'PKG_GIT_SHORT_COMMIT:=$$$${EXPECTED_PKG_GIT_SHORT_COMMIT}', found 'PKG_GIT_SHORT_COMMIT:=$(strip $(PKG_GIT_SHORT_COMMIT))'"; \
+			exit 1; \
+		fi \
+	)
 endef
 
 define Build/Compile
-	$(Build/PrepareJsonschema)
-	cd $(PKG_BUILD_DIR); \
-	$(GO_PKG_VARS) \
-	GITCOMMIT=$(PKG_GIT_SHORT_COMMIT) \
-	VERSION=$(PKG_VERSION) \
-	TARGET=$(PKG_BUILD_DIR)/build \
-	./scripts/build/binary
+	( \
+		cd $(PKG_BUILD_DIR); \
+		$(GO_PKG_VARS) \
+		GITCOMMIT=$(PKG_GIT_SHORT_COMMIT) \
+		VERSION=$(PKG_VERSION) \
+		./scripts/build/binary; \
+	)
 endef
 
 define Package/docker/install
